# Generated by Django 5.1.7 on 2025-04-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jucator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume_complet', models.CharField(max_length=100)),
                ('nationalitate', models.CharField(max_length=50)),
                ('titluri_castigate', models.IntegerField(default=0)),
                ('premii_bani_anul_curent', models.DecimalField(decimal_places=2, help_text='Premii în bani anul curent ($)', max_digits=12)),
                ('premii_bani_total', models.DecimalField(decimal_places=2, help_text='Total premii în bani ($)', max_digits=12)),
                ('debut_profesionist', models.IntegerField(help_text='Anul debutului profesionist')),
                ('varsta', models.IntegerField()),
                ('clasament_atp', models.IntegerField()),
                ('stil_joc', models.CharField(max_length=300)),
                ('greutate_kg', models.IntegerField()),
                ('inaltime_cm', models.IntegerField()),
                ('racheta_partener', models.CharField(max_length=100)),
                ('imagine_principala', models.ImageField(blank=True, null=True, upload_to='jucatori/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='jucatori/galerie/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='jucatori/galerie/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='jucatori/galerie/')),
            ],
        ),
    ]
