# Generated by Django 5.1.7 on 2025-04-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jucatori', '0002_alter_jucator_premii_bani_anul_curent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Cos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sesiune', models.CharField(max_length=100)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Coșuri',
            },
        ),
        migrations.CreateModel(
            name='Producator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='producatori/')),
            ],
            options={
                'verbose_name_plural': 'Producători',
            },
        ),
        migrations.CreateModel(
            name='Racheta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pret_redus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descriere_scurta', models.CharField(blank=True, max_length=255)),
                ('descriere', models.TextField()),
                ('specificatii', models.TextField(blank=True)),
                ('greutate', models.CharField(blank=True, max_length=50, null=True)),
                ('marime_cap', models.CharField(blank=True, max_length=50, null=True)),
                ('lungime', models.CharField(blank=True, max_length=50, null=True)),
                ('balans', models.CharField(blank=True, max_length=50, null=True)),
                ('tip_corzi', models.CharField(blank=True, max_length=100, null=True)),
                ('stoc', models.IntegerField(default=0)),
                ('imagine_principala', models.ImageField(upload_to='rachete/')),
                ('imagine_secundara', models.ImageField(blank=True, null=True, upload_to='rachete/')),
                ('imagine_tertiara', models.ImageField(blank=True, null=True, upload_to='rachete/')),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('in_stoc', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rachete', to='jucatori.categorie')),
                ('producator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rachete', to='jucatori.producator')),
            ],
            options={
                'verbose_name_plural': 'Rachete',
                'ordering': ['-data_adaugare'],
            },
        ),
        migrations.CreateModel(
            name='ItemCos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField(default=1)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('cos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jucatori.cos')),
                ('racheta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jucatori.racheta')),
            ],
            options={
                'verbose_name_plural': 'Itemi Coș',
            },
        ),
        migrations.CreateModel(
            name='ImagineRacheta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagine', models.ImageField(upload_to='rachete_imagini/')),
                ('este_principala', models.BooleanField(default=False)),
                ('ordine', models.IntegerField(default=0)),
                ('racheta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini', to='jucatori.racheta')),
            ],
            options={
                'verbose_name_plural': 'Imagini Rachete',
                'ordering': ['ordine'],
            },
        ),
    ]
